#define KEYWORDS_1364_1995 \
    { "always", TokenKind::AlwaysKeyword },\
    { "and", TokenKind::AndKeyword },\
    { "assign", TokenKind::AssignKeyword },\
    { "begin", TokenKind::BeginKeyword },\
    { "buf", TokenKind::BufKeyword },\
    { "bufif0", TokenKind::BufIf0Keyword },\
    { "bufif1", TokenKind::BufIf1Keyword },\
    { "case", TokenKind::CaseKeyword },\
    { "casex", TokenKind::CaseXKeyword },\
    { "casez", TokenKind::CaseZKeyword },\
    { "cmos", TokenKind::CmosKeyword },\
    { "deassign", TokenKind::DeassignKeyword },\
    { "default", TokenKind::DefaultKeyword },\
    { "defparam", TokenKind::DefParamKeyword },\
    { "disable", TokenKind::DisableKeyword },\
    { "edge", TokenKind::EdgeKeyword },\
    { "else", TokenKind::ElseKeyword },\
    { "end", TokenKind::EndKeyword },\
    { "endcase", TokenKind::EndCaseKeyword },\
    { "endfunction", TokenKind::EndFunctionKeyword },\
    { "endmodule", TokenKind::EndModuleKeyword },\
    { "endprimitive", TokenKind::EndPrimitiveKeyword },\
    { "endspecify", TokenKind::EndSpecifyKeyword },\
    { "endtable", TokenKind::EndTableKeyword },\
    { "endtask", TokenKind::EndTaskKeyword },\
    { "event", TokenKind::EventKeyword },\
    { "for", TokenKind::ForKeyword },\
    { "force", TokenKind::ForceKeyword },\
    { "forever", TokenKind::ForeverKeyword },\
    { "fork", TokenKind::ForkKeyword },\
    { "function", TokenKind::FunctionKeyword },\
    { "highz0", TokenKind::HighZ0Keyword },\
    { "highz1", TokenKind::HighZ1Keyword },\
    { "if", TokenKind::IfKeyword },\
    { "ifnone", TokenKind::IfNoneKeyword },\
    { "initial", TokenKind::InitialKeyword },\
    { "inout", TokenKind::InOutKeyword },\
    { "input", TokenKind::InputKeyword },\
    { "integer", TokenKind::IntegerKeyword },\
    { "join", TokenKind::JoinKeyword },\
    { "large", TokenKind::LargeKeyword },\
    { "macromodule", TokenKind::MacromoduleKeyword },\
    { "medium", TokenKind::MediumKeyword },\
    { "module", TokenKind::ModuleKeyword },\
    { "nand", TokenKind::NandKeyword },\
    { "negedge", TokenKind::NegEdgeKeyword },\
    { "nmos", TokenKind::NmosKeyword },\
    { "nor", TokenKind::NorKeyword },\
    { "not", TokenKind::NotKeyword },\
    { "notif0", TokenKind::NotIf0Keyword },\
    { "notif1", TokenKind::NotIf1Keyword },\
    { "or", TokenKind::OrKeyword },\
    { "output", TokenKind::OutputKeyword },\
    { "parameter", TokenKind::ParameterKeyword },\
    { "pmos", TokenKind::PmosKeyword },\
    { "posedge", TokenKind::PosEdgeKeyword },\
    { "primitive", TokenKind::PrimitiveKeyword },\
    { "pull0", TokenKind::Pull0Keyword },\
    { "pull1", TokenKind::Pull1Keyword },\
    { "pulldown", TokenKind::PullDownKeyword },\
    { "pullup", TokenKind::PullUpKeyword },\
    { "rcmos", TokenKind::RcmosKeyword },\
    { "real", TokenKind::RealKeyword },\
    { "realtime", TokenKind::RealTimeKeyword },\
    { "reg", TokenKind::RegKeyword },\
    { "release", TokenKind::ReleaseKeyword },\
    { "repeat", TokenKind::RepeatKeyword },\
    { "rnmos", TokenKind::RnmosKeyword },\
    { "rpmos", TokenKind::RpmosKeyword },\
    { "rtran", TokenKind::RtranKeyword },\
    { "rtranif0", TokenKind::RtranIf0Keyword },\
    { "rtranif1", TokenKind::RtranIf1Keyword },\
    { "scalared", TokenKind::ScalaredKeyword },\
    { "small", TokenKind::SmallKeyword },\
    { "specify", TokenKind::SpecifyKeyword },\
    { "specparam", TokenKind::SpecParamKeyword },\
    { "strong0", TokenKind::Strong0Keyword },\
    { "strong1", TokenKind::Strong1Keyword },\
    { "supply0", TokenKind::Supply0Keyword },\
    { "supply1", TokenKind::Supply1Keyword },\
    { "table", TokenKind::TableKeyword },\
    { "task", TokenKind::TaskKeyword },\
    { "time", TokenKind::TimeKeyword },\
    { "tran", TokenKind::TranKeyword },\
    { "tranif0", TokenKind::TranIf0Keyword },\
    { "tranif1", TokenKind::TranIf1Keyword },\
    { "tri", TokenKind::TriKeyword },\
    { "tri0", TokenKind::Tri0Keyword },\
    { "tri1", TokenKind::Tri1Keyword },\
    { "triand", TokenKind::TriAndKeyword },\
    { "trior", TokenKind::TriOrKeyword },\
    { "trireg", TokenKind::TriRegKeyword },\
    { "vectored", TokenKind::VectoredKeyword },\
    { "wait", TokenKind::WaitKeyword },\
    { "wand", TokenKind::WAndKeyword },\
    { "weak0", TokenKind::Weak0Keyword },\
    { "weak1", TokenKind::Weak1Keyword },\
    { "while", TokenKind::WhileKeyword },\
    { "wire", TokenKind::WireKeyword },\
    { "wor", TokenKind::WOrKeyword },\
    { "xor", TokenKind::XorKeyword },\
    { "xnor", TokenKind::XnorKeyword }
    